# Generated by Django 3.0.8 on 2020-10-01 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200924_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='species',
            field=models.ManyToManyField(related_name='shelters', related_query_name='shelter', to='projects.PetTag'),
        ),
    ]
